import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Seeding 10 packages + itineraries...');

    // ─── Agency 1 ───────────────────────────────────────────────────────────
    const agency1 = await prisma.agency.upsert({
        where: { cnpj: '12.345.678/0001-01' },
        update: {},
        create: {
            name: 'Wanderlust Premium Travel',
            cnpj: '12.345.678/0001-01',
            logo: 'https://ui-avatars.com/api/?name=Wanderlust&background=28C9BF&color=fff&bold=true&size=128',
            contactUrl: 'https://wanderlust.com.br',
            whatsapp: '+55 11 99999-0001',
            city: 'São Paulo',
            state: 'SP',
            verified: true,
            plan: 'FREE',
        },
    });

    const agency2 = await prisma.agency.upsert({
        where: { cnpj: '98.765.432/0001-02' },
        update: {},
        create: {
            name: 'Horizonte Viagens',
            cnpj: '98.765.432/0001-02',
            logo: 'https://ui-avatars.com/api/?name=Horizonte&background=6366F1&color=fff&bold=true&size=128',
            contactUrl: 'https://horizonteviagens.com.br',
            whatsapp: '+55 21 99999-0002',
            city: 'Rio de Janeiro',
            state: 'RJ',
            verified: true,
            plan: 'FREE',
        },
    });

    // ─── Employee for agency1 ──────────────────────────────────────────────
    const passwordHash = await bcrypt.hash('vamo123', 10);
    await prisma.agencyEmployee.upsert({
        where: { email: 'admin@vamo.com' },
        update: {},
        create: {
            agencyId: agency1.id,
            name: 'Diego Artur',
            email: 'admin@vamo.com',
            passwordHash,
            role: 'MANAGER',
        },
    });

    // ─── Traveler + Creator ────────────────────────────────────────────────
    const traveler1 = await prisma.traveler.upsert({
        where: { email: 'lara@vamo.com' },
        update: {},
        create: {
            name: 'Lara Campos',
            email: 'lara@vamo.com',
            passwordHash: await bcrypt.hash('vamo123', 10),
            bio: 'Viajei para 40 países e sou apaixonada por roteiros autênticos fora do óbvio.',
            avatar: 'https://ui-avatars.com/api/?name=Lara+Campos&background=F472B6&color=fff&bold=true&size=128',
        },
    });

    const creator1 = await prisma.creator.upsert({
        where: { travelerId: traveler1.id },
        update: {},
        create: {
            travelerId: traveler1.id,
            bio: 'Sou criadora de roteiros independentes, com foco em experiências autênticas e planejamento inteligente.',
            verificationLevel: 'EXPERT',
            destinations: ['Portugal', 'Grécia', 'Japão', 'Marrocos', 'Tailândia'],
            languages: ['Português', 'Inglês', 'Espanhol'],
            totalSales: 873,
            averageRating: 4.9,
            responseTime: '< 2h',
            tripsCompleted: 40,
        },
    });

    const traveler2 = await prisma.traveler.upsert({
        where: { email: 'rafael@vamo.com' },
        update: {},
        create: {
            name: 'Rafael Menezes',
            email: 'rafael@vamo.com',
            passwordHash: await bcrypt.hash('vamo123', 10),
            bio: 'Mochileiro profissional. Já fui a 55 países com orçamento enxuto.',
            avatar: 'https://ui-avatars.com/api/?name=Rafael+Menezes&background=10B981&color=fff&bold=true&size=128',
        },
    });

    const creator2 = await prisma.creator.upsert({
        where: { travelerId: traveler2.id },
        update: {},
        create: {
            travelerId: traveler2.id,
            bio: 'Especialista em viagens com custo-benefício máximo. Meus roteiros são direto ao ponto: o que fazer, onde comer e como economizar.',
            verificationLevel: 'TRUSTED',
            destinations: ['Argentina', 'Colômbia', 'Costa Rica', 'México', 'Vietnã'],
            languages: ['Português', 'Inglês'],
            totalSales: 1240,
            averageRating: 4.8,
            responseTime: '< 4h',
            tripsCompleted: 55,
        },
    });

    // ─── 5 PACKAGES ────────────────────────────────────────────────────────────

    const packages = [
        {
            agencyId: agency1.id,
            title: 'Paris & Côte d\'Azur — Romance Absoluto',
            destination: 'Paris',
            country: 'França',
            description: 'Uma jornada inesquecível por duas das regiões mais românticas do mundo. De Paris e seus bistrôs a Niza e as praias da Riviera Francesa.',
            fullDescription: 'Comece sua viagem em Paris com 5 noites em hotel boutique no Marais. Depois, pegue o trem de alta velocidade até Niza e explore a deslumbrante Costa Azul: Mônaco, Cannes e as vilas medievais do interior. Alimentação em restaurantes curados, transfers privados e guia bilíngue inclusos.',
            emotionalIntro: 'Imagine acordar com vista para a Torre Eiffel, almoçar em um bistrô parisiense e jantar com os pés na areia em Cannes. Isso não é só uma viagem — é a vida que você merece.',
            currency: 'BRL',
            duration: 10,
            nights: 9,
            priceMin: 12800,
            priceMax: 16900,
            continent: 'Europa',
            airport: 'CDG',
            travelStyles: ['Romântico', 'Luxo'],
            categories: ['Europa', 'Casais', 'Gastronomia', 'Cultura'],
            includes: ['Voo incluso', 'Hotel 4★', 'Transfers', 'Guia bilíngue', 'Café da manhã'],
            includedItems: ['Passeio de barco no Sena', 'Ingresso Museu do Louvre', 'Day trip a Mônaco', 'Trem Paris–Niza'],
            highlights: ['Torre Eiffel à noite', 'Bistrôs secretos no Marais', 'Praias de Cannes', 'Port de Mônaco'],
            perfectFor: ['Casais em lua de mel', 'Comemorações especiais', 'Amantes de gastronomia'],
            notRecommendedFor: ['Famílias com crianças pequenas', 'Viajantes com orçamento limitado'],
            importantInfo: ['Passaporte com validade mínima 6 meses', 'Visto Schengen necessário para passaporte brasileiro'],
            featured: true,
            hasFreeCancellation: true,
            isAllInclusive: false,
            badge: 'BESTSELLER',
            rating: 4.9,
            reviewCount: 127,
            recentPurchases: 23,
            qualityScore: 95,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency1.id,
            title: 'Japão dos Cerejeiras — 14 Dias Completos',
            destination: 'Tóquio',
            country: 'Japão',
            description: 'A viagem completa pelo Japão: Tóquio, Kyoto, Osaka e Hiroshima. Cultura milenar, gastronomia única e a magia das cerejeiras em flor.',
            fullDescription: 'Roteiro cuidadosamente planejado para absorver o máximo do Japão. Comece em Tóquio (5 noites), explore a modernidade de Shibuya e a tradição de Asakusa. Siga para o Monte Fuji e Kyoto (4 noites) com templos, gueixas e jardins zen. Termine em Osaka com os melhores takoyakis do mundo.',
            emotionalIntro: 'O Japão não é um destino. É uma experiência que muda você por dentro. Cada detalhe — do bullet train ao ramen fumegante numa noite fria em Kyoto — fica gravado para sempre.',
            currency: 'BRL',
            duration: 14,
            nights: 13,
            priceMin: 16800,
            priceMax: 22500,
            continent: 'Ásia',
            airport: 'NRT',
            travelStyles: ['Cultural', 'Gastronomia', 'Luxo'],
            categories: ['Ásia', 'Cultural', 'Gastronomia', 'Solo', 'Casais'],
            includes: ['Voo incluso', 'Hotel 3-4★', 'JR Pass 14 dias', 'Guia local', 'Café da manhã'],
            includedItems: ['JR Pass para bullet trains', 'Passeio ao Monte Fuji', 'Cerimônia do chá', 'Mercado Tsukiji', 'Day trip a Nara'],
            highlights: ['Cherry Blossom em Maruyama', 'Shibuya Crossing à noite', 'Fushimi Inari ao amanhecer', 'Kyoto de quimono'],
            perfectFor: ['Apaixonados por cultura', 'Fotógrafos', 'Gastrônomos', 'Solo travelers'],
            notRecommendedFor: ['Quem tem pouca mobilidade física', 'Crianças abaixo de 5 anos'],
            importantInfo: ['Brasileiros não precisam de visto para o Japão', 'Melhor época: março–abril (cerejeiras) ou out–nov (outono)'],
            featured: true,
            hasFreeCancellation: false,
            isAllInclusive: false,
            badge: 'FEATURED',
            rating: 4.9,
            reviewCount: 89,
            recentPurchases: 15,
            qualityScore: 97,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency2.id,
            title: 'Maldivas Overwater — All Inclusive',
            destination: 'Maldivas',
            country: 'Maldivas',
            description: 'A experiência definitiva de bangalô sobre as águas. 7 noites em resort 5★ com all inclusive completo, snorkel, mergulho e pôr do sol inesquecível.',
            fullDescription: 'Escolhemos os melhores resorts das Maldivas para você. Bangalô overwater com deck privativo, acesso direto ao oceano e lagoa cristalina. All inclusive total: refeições gourmet, open bar, snorkel, kayak, mergulho supervisionado e passeio de dhoni ao pôr do sol.',
            emotionalIntro: 'Abra a porta do seu bangalô e pule direto no Oceano Índico. As Maldivas são o único lugar no mundo onde o paraíso não é só uma palavra — é literal.',
            currency: 'BRL',
            duration: 9,
            nights: 8,
            priceMin: 18500,
            priceMax: 28000,
            continent: 'Ásia',
            airport: 'MLE',
            travelStyles: ['Luxo', 'Romântico'],
            categories: ['Praia', 'Luxo', 'Casais', 'All Inclusive', 'Mergulho'],
            includes: ['Voo incluso', 'Bangalô overwater 5★', 'All Inclusive total', 'Transfer de speedboat', 'Snorkel e mergulho'],
            includedItems: ['Open bar premium', 'Massagem de boas-vindas', 'Passeio de dhoni', 'Observação de bioluminescência', 'Mergulho supervisionado'],
            highlights: ['Bangalô about the water', 'Tartarugas marinhas selvagens', 'Pôr do sol no Oceano Índico', 'Jantar na praia'],
            perfectFor: ['Lua de mel', 'Aniversários especiais', 'Quem sempre quis ir às Maldivas'],
            notRecommendedFor: ['Famílias com crianças pequenas', 'Viajantes que preferem cidades'],
            importantInfo: ['Passaporte com validade mínima 6 meses', 'Moeda local: Rufiyaa mas dólar é aceito amplo'],
            featured: true,
            hasFreeCancellation: true,
            isAllInclusive: true,
            badge: 'LUXURY',
            rating: 4.95,
            reviewCount: 64,
            recentPurchases: 8,
            qualityScore: 99,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency2.id,
            title: 'Patagônia Selvagem — Argentina & Chile',
            destination: 'El Calafate',
            country: 'Argentina',
            description: 'A aventura da vida nas paisagens mais dramáticas do planeta. Torres del Paine, Glaciar Perito Moreno, Ushuaia e o fim do mundo.',
            fullDescription: 'Pacote de aventura premium pela Patagônia argentina e chilena. Comece em Buenos Aires (2 noites), voe para El Calafate e o lendário Glaciar Perito Moreno, cruce a fronteira para o Parque Nacional Torres del Paine (trekking W opcional), e termine em Ushuaia, a cidade mais austral do mundo.',
            emotionalIntro: 'Ficar de frente para o Perito Moreno e ouvir o gelo se despedaçar. Caminhar até a base das Torres del Paine com o vento na face. Isso é a Patagônia: bruta, linda e inesquecível.',
            currency: 'BRL',
            duration: 15,
            nights: 14,
            priceMin: 9800,
            priceMax: 14500,
            continent: 'América do Sul',
            airport: 'EZE',
            multiDestination: true,
            additionalCities: ['El Calafate', 'Puerto Natales', 'Ushuaia'],
            travelStyles: ['Aventura', 'Natureza'],
            categories: ['Aventura', 'Natureza', 'América do Sul', 'Trekking'],
            includes: ['Voos internos', 'Hotel 3★', 'Transfers', 'Guia de trekking', 'Entradas parques'],
            includedItems: ['Cruzeiro pelo glaciar Perito Moreno', 'Trekking Base das Torres', 'Navegação Beagle', 'Entrada Parque Torres del Paine'],
            highlights: ['Perito Moreno ao vivo', 'Torres del Paine ao nascer do sol', 'Fim do mundo em Ushuaia', 'Fauna patagônica'],
            perfectFor: ['Aventureiros', 'Amantes de trekking', 'Naturalistas', 'Solo travelers'],
            notRecommendedFor: ['Pessoas com dificuldades físicas', 'Quem prefere cidades e praias'],
            importantInfo: ['Melhor época: outubro a março', 'Clima imprevisível — traga roupas em camadas', 'Brasileiros não precisam de visto'],
            featured: false,
            hasFreeCancellation: false,
            isAllInclusive: false,
            badge: 'VERIFIED',
            rating: 4.8,
            reviewCount: 43,
            recentPurchases: 6,
            qualityScore: 88,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency1.id,
            title: 'Dubai Futurista — 8 Dias de Puro Luxo',
            destination: 'Dubai',
            country: 'Emirados Árabes',
            description: 'Dubai é a cidade do impossível. Arranha-céus, desertos dourados, ilhas artificiais e shopping que parecem aeroportos. Esta é a viagem que você vai contar pra sempre.',
            fullDescription: 'Roteiro Dubai completo: Burj Khalifa, Desert Safari, Dubai Mall, Palm Jumeirah, Museu do Futuro e Dubai Creek histórico. Hotel 5★ com vista para o Burj ou a Marina. Opção de extensão para Abu Dhabi com Grand Mosque e Ferrari World.',
            emotionalIntro: 'Subir no edifício mais alto do mundo ao pôr do sol. Dormir numa ilha artificial no Golfo Pérsico. Jantar num restaurante flutuante. Dubai não é só uma viagem — é um flex de vida.',
            currency: 'BRL',
            duration: 8,
            nights: 7,
            priceMin: 12200,
            priceMax: 18800,
            continent: 'Ásia',
            airport: 'DXB',
            travelStyles: ['Luxo', 'Cultural'],
            categories: ['Luxo', 'City Trip', 'Casais', 'Amigos'],
            includes: ['Voo incluso', 'Hotel 5★', 'Desert Safari', 'Transfers', 'Ingressos Burj Khalifa'],
            includedItems: ['Desert Safari com jantar beduíno', 'Burj Khalifa At The Top', 'Cruzeiro Dubai Marina', 'Day trip Abu Dhabi'],
            highlights: ['Burj Khalifa 148° andar', 'Deserto do Dubai ao pôr do sol', 'Dubai Mall indoor ski', 'Palm Jumeirah vista aérea'],
            perfectFor: ['Quem nunca foi a Dubai', 'Apreciadores de luxo e modernidade', 'Grupos de amigos e casais'],
            notRecommendedFor: ['Viajantes com orçamento muito limitado', 'Quem prefere natureza e aventura'],
            importantInfo: ['Ramadã altera horários — verifique datas', 'Vestimenta conservadora em mesquitas', 'Brasileiros não precisam de visto'],
            featured: true,
            hasFreeCancellation: true,
            isAllInclusive: false,
            badge: 'LUXURY',
            rating: 4.85,
            reviewCount: 56,
            recentPurchases: 12,
            qualityScore: 93,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
    ];

    for (const pkg of packages) {
        const existing = await prisma.package.findFirst({ where: { title: pkg.title } });
        if (!existing) {
            await prisma.package.create({ data: pkg as any });
            console.log(`✅ Pacote criado: ${pkg.title}`);
        } else {
            console.log(`⏭️  Pacote já existe: ${pkg.title}`);
        }
    }

    // ─── 5 ITINERARIES ────────────────────────────────────────────────────────

    const itineraries = [
        {
            creatorId: creator1.id,
            title: 'Lisboa Secreta — 7 Dias Como um Local',
            destination: 'Lisboa',
            country: 'Portugal',
            description: 'Esqueça os guias turísticos básicos. Este roteiro te leva aos mercados escondidos, restaurantes sem placa e mirantes que só os lisboetas conhecem.',
            subtitle: 'A Lisboa que os turistas não veem — mas você vai conhecer.',
            currency: 'BRL',
            price: 89,
            duration: 7,
            travelStyles: ['Cultural', 'Gastronômico'],
            categories: ['Europa', 'Solo', 'Casais', 'Gastronômico'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'gasto', 'restaurantes', 'dicas', 'checklist'],
            highlights: ['Bairro de Mouraria ao amanhecer', 'Mercado de Campo de Ourique', 'Fado ao vivo em Alfama', 'Restaurantes sem placa no Intendente'],
            inclusions: ['Roteiro dia a dia', 'Mapa interativo', 'Lista de restaurantes locais', 'Guia de frases em português europeu', 'Planilha de gastos'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 94,
            featured: true,
            rating: 4.95,
            reviewCount: 312,
            downloadCount: 873,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 120, max: 200, currency: 'EUR',
                breakdown: [
                    { category: 'Hospedagem', amount: 65, description: 'Hostel premium ou Airbnb no centro histórico' },
                    { category: 'Alimentação', amount: 35, description: 'Pastelarias + restaurantes locais + mercados' },
                    { category: 'Transporte', amount: 15, description: 'Metro + elétrico 28 + uber' },
                    { category: 'Atrações', amount: 25, description: 'Museus + Sintra day trip' },
                    { category: 'Extras', amount: 20, description: 'Souvenirs + imprevistos' },
                ],
            },
        },
        {
            creatorId: creator2.id,
            title: 'Buenos Aires em 6 Dias — Tango, Bife e Malbec',
            destination: 'Buenos Aires',
            country: 'Argentina',
            description: 'O roteiro definitivo para quem quer curtir Buenos Aires de verdade: parrillas escondidas, shows de tango autênticos, barrios criativos e vinhos incríveis.',
            subtitle: 'De Palermo a San Telmo — a cidade que não dorme.',
            currency: 'BRL',
            price: 59,
            duration: 6,
            travelStyles: ['Cultural', 'Gastronômico'],
            categories: ['América do Sul', 'Solo', 'Casais', 'Amigos', 'Gastronômico'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'restaurantes', 'dicas', 'checklist', 'gasto'],
            highlights: ['Parrilla reservada só com QR code no roteiro', 'Tango ao vivo no La Catedral', 'Feira de San Telmo', 'Vinho Malbec na vinícola Mendoza'],
            inclusions: ['Roteiro dia a dia', 'Lista de bares ocultos', 'Dica de câmbio (economize até 60%)', 'Guia de sobrevivência portenha'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 88,
            featured: false,
            rating: 4.85,
            reviewCount: 187,
            downloadCount: 540,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 60, max: 120, currency: 'USD',
                breakdown: [
                    { category: 'Hospedagem', amount: 40, description: 'Hostel boutique em Palermo ou San Telmo' },
                    { category: 'Alimentação', amount: 30, description: 'Bife de chorizo, empanadas, medialunas' },
                    { category: 'Transporte', amount: 10, description: 'SUBE (metrô) + Uber quando necessário' },
                    { category: 'Shows', amount: 20, description: 'Tango + cervejaria artesanal' },
                    { category: 'Extras', amount: 20, description: 'Compras no Mercado de Pulgas' },
                ],
            },
        },
        {
            creatorId: creator1.id,
            title: 'Grécia Completa — Atenas, Santorini e Mykonos',
            destination: 'Atenas',
            country: 'Grécia',
            description: 'O roteiro mais completo da Grécia: ruins milenares em Atenas, pôr do sol de Santorini e o balada de Mykonos. 12 dias de paraíso.',
            subtitle: 'Deuses, ruínas, praias e o melhor pôr do sol do mundo.',
            currency: 'BRL',
            price: 129,
            duration: 12,
            travelStyles: ['Cultural', 'Praia', 'Romântico'],
            categories: ['Europa', 'Casais', 'Amigos', 'Praia', 'Cultural'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'gasto', 'restaurantes', 'dicas', 'checklist'],
            highlights: ['Acropole sem filas (dica do roteiro)', 'Pôr do sol em Oia, Santorini', 'Ferry Athens–Santorini–Mykonos', 'Praia de Mykonos: Super Paradise'],
            inclusions: ['Roteiro completo 12 dias', 'Mapa offline das ilhas', 'Guia de ferries com preços', 'Hospedagem recomendada por orçamento', 'Frases em grego'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 96,
            featured: true,
            rating: 4.9,
            reviewCount: 428,
            downloadCount: 1240,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 150, max: 280, currency: 'EUR',
                breakdown: [
                    { category: 'Hospedagem', amount: 100, description: 'De hostel (15€/noite) a cave hotel em Santorini (80€+)' },
                    { category: 'Ferries', amount: 60, description: 'Atenas–Santorini–Mykonos–Atenas' },
                    { category: 'Alimentação', amount: 50, description: 'Gyros (3€) a tavernas locais (25€/pessoa)' },
                    { category: 'Atrações', amount: 30, description: 'Acropole + Museu + passeios de barco' },
                    { category: 'Extras', amount: 40, description: 'Drinks + souvenirs + imprevistos' },
                ],
            },
        },
        {
            creatorId: creator2.id,
            title: 'Tailândia do Norte ao Sul em 14 Dias',
            destination: 'Bangkok',
            country: 'Tailândia',
            description: 'Bangkok, Chiang Mai, as ilhas do sul. Este roteiro cobre o melhor da Tailândia num ritmo perfeito — sem pressa, mas sem perder nada importante.',
            subtitle: 'Dos templos dourados às praias paradisíacas',
            currency: 'BRL',
            price: 119,
            duration: 14,
            travelStyles: ['Aventura', 'Cultural', 'Praia'],
            categories: ['Ásia', 'Solo', 'Casais', 'Aventura', 'Praia'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'gasto', 'restaurantes', 'dicas', 'checklist'],
            highlights: ['Mercado flutuante Damnoen Saduak', 'Aula de culinária thai em Chiang Mai', 'Phi Phi Islands', 'Full Moon Party em Koh Phangan'],
            inclusions: ['Roteiro 14 dias', 'Mapa com transportes terrestres e marítimos', 'Aplicativos essenciais para a Tailândia', 'Lista negra: o que NÃO fazer', 'Guia de street food seguro'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 91,
            featured: false,
            rating: 4.87,
            reviewCount: 265,
            downloadCount: 892,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 800, max: 1500, currency: 'BRL',
                breakdown: [
                    { category: 'Hospedagem', amount: 400, description: 'Hostels e guesthouses (R$30–120/noite)' },
                    { category: 'Alimentação', amount: 250, description: 'Street food + restaurantes (R$10–40/refeição)' },
                    { category: 'Transporte', amount: 300, description: 'Voos internos + ferries + tuk-tuks' },
                    { category: 'Atrações', amount: 250, description: 'Templos + passeios + aulas culinária' },
                    { category: 'Extras', amount: 300, description: 'Massagens + compras + coco na praia' },
                ],
            },
        },
        {
            creatorId: creator1.id,
            title: 'Marrocos Mágico — 10 Dias nos Souks e Deserto',
            destination: 'Marrakech',
            country: 'Marrocos',
            description: 'Das medinas labirínticas de Marrakech ao silêncio do Saara. Este roteiro é para quem quer se perder de propósito e descobrir um mundo completamente diferente.',
            subtitle: 'Cores, cheiros, sonhos — bem-vindo ao Marrocos.',
            currency: 'BRL',
            price: 109,
            duration: 10,
            travelStyles: ['Aventura', 'Cultural'],
            categories: ['África', 'Solo', 'Casais', 'Cultural', 'Aventura'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'dicas', 'checklist'],
            highlights: ['Noite no deserto do Saara em tenda berber', 'Souk de Marrakech: negociar como local', 'Chefchaouen — a cidade azul', 'Cascata Ouzoud'],
            inclusions: ['Roteiro 10 dias', 'Guia de negociação nos souks', 'Dicas de segurança', 'Frases em árabe e francês', 'Lista de riads autênticos'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 90,
            featured: false,
            rating: 4.82,
            reviewCount: 143,
            downloadCount: 421,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 100, max: 180, currency: 'EUR',
                breakdown: [
                    { category: 'Hospedagem', amount: 50, description: 'Riads autênticos (20–60€/noite)' },
                    { category: 'Alimentação', amount: 25, description: 'Tagine + chá + street food (5–20€/refeição)' },
                    { category: 'Transporte', amount: 30, description: 'CTM bus + grand taxi + dromedário no Saara' },
                    { category: 'Noite no Deserto', amount: 40, description: 'Tenda berber com jantar e café da manhã' },
                    { category: 'Compras', amount: 35, description: 'Artesanato, babuchas e especiarias' },
                ],
            },
        },
    ];

    for (const it of itineraries) {
        const existing = await prisma.itinerary.findFirst({ where: { title: it.title } });
        if (!existing) {
            await prisma.itinerary.create({ data: it as any });
            console.log(`✅ Roteiro criado: ${it.title}`);
        } else {
            console.log(`⏭️  Roteiro já existe: ${it.title}`);
        }
    }

    console.log('\n🎉 Seed completo!');
    console.log(`📦 5 pacotes premium`);
    console.log(`🗺️  5 roteiros detalhados`);
    console.log(`👤 2 agências, 2 criadores`);
}

main()
    .catch(e => { console.error(e); process.exit(1); })
    .finally(() => prisma.$disconnect());
