import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
    console.log('🌱 Seeding 5 more packages + 5 more itineraries...');

    const agency1 = await prisma.agency.findFirst({ where: { cnpj: '12.345.678/0001-01' } });
    const agency2 = await prisma.agency.findFirst({ where: { cnpj: '98.765.432/0001-02' } });
    const creator1 = await prisma.creator.findFirst({ include: { traveler: true } });
    const creator2 = await prisma.creator.findMany({ include: { traveler: true } });

    if (!agency1 || !agency2 || !creator1) {
        console.error('❌ Run seed-demo.ts first to create agencies and creators');
        return;
    }

    const creators = creator2;

    // ─── 5 NOVOS PACOTES ────────────────────────────────────────────────────────

    const packages = [
        {
            agencyId: agency1.id,
            title: 'Toscana & Roma — La Dolce Vita',
            destination: 'Florença',
            country: 'Itália',
            description: 'Vinhedos dourados, cidades medievais, pasta feita à mão e o melhor vinho do mundo. Esta é a viagem que vai fazer você entender por que os italianos não têm pressa.',
            fullDescription: 'Chegue em Roma (3 noites): Vaticano, Coliseu, Trastevere à noite. Treno para Florença (3 noites): Uffizi, Duomo, gelato real. Depois, alugue um carro e se perca pela Toscana rural: Siena, San Gimignano, vinícola no Chianti, trufas em Pienza.',
            emotionalIntro: 'Acordar num agriturismo com vista para ciprestes. Almoçar pappardelle com ragù feito pela nonna. Beber Brunello de Montalcino no pôr do sol. A Itália não é um país — é um sentimento.',
            currency: 'AUD',
            duration: 12,
            nights: 11,
            priceMin: 3800,
            priceMax: 5600,
            continent: 'Europa',
            airport: 'FCO',
            multiDestination: true,
            additionalCities: ['Roma', 'Siena', 'San Gimignano', 'Pienza'],
            travelStyles: ['Gastronômico', 'Cultural', 'Romântico'],
            categories: ['Europa', 'Casais', 'Gastronomia', 'Cultural', 'Vinho'],
            includes: ['Voo incluso', 'Hotel 4★ + Agriturismo', 'Carro alugado na Toscana', 'Degustação de vinhos', 'Café da manhã'],
            includedItems: ['Vaticano e Museus do Vaticano', 'Uffizi Gallery em Florença', 'Degustação Chianti', 'Trufas e queijos em Pienza', 'Cooking class de pasta'],
            highlights: ['Tramonto no Campo de Siena', 'Leonardo da Vinci no Uffizi', 'Gelato às 2h no Trastevere', 'Vinícola familiar no Chianti'],
            perfectFor: ['Casal em lua de mel', 'Amantes de gastronomia e vinho', 'Apreciadores de arte e história'],
            notRecommendedFor: ['Quem tem pressa', 'Viajantes com orçamento muito limitado'],
            importantInfo: ['Melhor época: abril–junho e set–out', 'Motorista precisa de carteira internacional', 'Visto Schengen obrigatório'],
            featured: true,
            hasFreeCancellation: true,
            isAllInclusive: false,
            badge: 'BESTSELLER',
            rating: 4.92,
            reviewCount: 98,
            recentPurchases: 19,
            qualityScore: 96,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency2.id,
            title: 'Safari no Quênia — Grande Migração',
            destination: 'Nairóbi',
            country: 'Quênia',
            description: 'Ver 2 milhões de gnus cruzando o Mara. Leão caçando ao amanhecer. Elefantes no poente. Isto não é um passeio — é a experiência mais brutal e bonita que você vai ter na vida.',
            fullDescription: 'Safari completo pelo Quênia: Masai Mara (campo privado), Lake Nakuru (flamingos rosa e rinocerontes), Amboseli com vista para o Kilimanjaro. Hospedagem em lodges e tented camps de luxo, guias nativos especializados, todos os safáris incluídos.',
            emotionalIntro: 'Na savana, o tempo para. Um elefante passa a 3 metros do seu jeep. Você segura o fôlego. Isto é o Quênia — e vai mudar a sua percepção do que é ser vivo.',
            currency: 'AUD',
            duration: 10,
            nights: 9,
            priceMin: 7200,
            priceMax: 10800,
            continent: 'África',
            airport: 'NBO',
            travelStyles: ['Aventura', 'Natureza', 'Luxo'],
            categories: ['Aventura', 'Natureza', 'África', 'Luxo', 'Fauna'],
            includes: ['Voo incluso', 'Lodge e Tented Camp 5★', 'Todos os safáris', 'Guia nativo certificado', 'Pensão completa'],
            includedItems: ['Safári Big 5 no Masai Mara', 'Visita à aldeia Masai', 'Flamingos no Lake Nakuru', 'Kilimanjaro ao fundo no Amboseli', 'Noite de observação estelar'],
            highlights: ['Grande Migração (jul–out)', 'Big 5 em liberdade', 'Pôr do sol na savana', 'Tented camp de luxo'],
            perfectFor: ['Quem sonha com África', 'Naturalistas e fotógrafos', 'Casal em experiência única'],
            notRecommendedFor: ['Crianças pequenas', 'Quem tem medo de animais selvagens'],
            importantInfo: ['Vacinas: febre amarela obrigatória', 'Melhor época: jul–out (Grande Migração)', 'Visto on arrival no Quênia'],
            featured: true,
            hasFreeCancellation: false,
            isAllInclusive: true,
            badge: 'LUXURY',
            rating: 4.97,
            reviewCount: 41,
            recentPurchases: 5,
            qualityScore: 98,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency1.id,
            title: 'Islândia — Aurora Boreal e Fiordes',
            destination: 'Reykjavik',
            country: 'Islândia',
            description: 'Gêiseres, cachoeiras, geleiras azuis, orcas e a magia das auroras boreais. A Islândia é o lugar onde a natureza exibe seu poder sem filtros.',
            fullDescription: 'Ring Road completa pela Islândia: Reykjavik, Círculo Dourado (Geysir, Gullfoss, Þingvellir), Costa Sul (Seljalandsfoss, Skógafoss, praia negra), Glacier Lagoon Jökulsárlón, Eastfjords e Akureyri. Carro 4x4 incluso. Saídas de setembro a março para garantir aurora boreal.',
            emotionalIntro: 'Não existe preparação para a sua primeira aurora boreal. O céu começa a dançar em verde e roxo e você simplesmente congela — com frio e com emoção.',
            currency: 'AUD',
            duration: 10,
            nights: 9,
            priceMin: 4700,
            priceMax: 6600,
            continent: 'Europa',
            airport: 'KEF',
            travelStyles: ['Aventura', 'Natureza'],
            categories: ['Aventura', 'Natureza', 'Europa', 'Fotografia', 'Solo'],
            includes: ['Voo incluso', 'Hotel e Guesthouses', '4x4 incluso', 'Mapa Ring Road', 'Botas impermeáveis'],
            includedItems: ['Tour da Aurora Boreal', 'Mergulho em Silfra (Þingvellir)', 'Glacier Walk', 'Whale watching em Husavik', 'Lagoa Azul'],
            highlights: ['Aurora Boreal (set–mar)', 'Geleiras de mil anos', 'Cachoeira Seljalandsfoss por dentro', 'Jökulsárlón ao golden hour'],
            perfectFor: ['Aventureiros fotógrafos', 'Amantes de natureza extrema', 'Solo travelers'],
            notRecommendedFor: ['Quem prefere praia e calor', 'Viajantes sem mobilidade física'],
            importantInfo: ['Melhor aurora: set–mar (noites escuras)', 'Motorista com carteira internacional', 'Visto Schengen necessário'],
            featured: false,
            hasFreeCancellation: false,
            isAllInclusive: false,
            badge: 'FEATURED',
            rating: 4.88,
            reviewCount: 72,
            recentPurchases: 9,
            qualityScore: 91,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency2.id,
            title: 'Bali Holístico — Templos, Praias e Yoga',
            destination: 'Ubud',
            country: 'Indonésia',
            description: 'Bali é o único lugar do mundo onde você consegue fazer yoga na terraça de um templo ao amanhecer e depois surfar no pôr do sol. Este pacote é para desacelerar com estilo.',
            fullDescription: 'Bali completo: Ubud (arrozais, templos, retiro de yoga), Seminyak (praias premium, beach clubs, gastronomia), Nusa Lembongan (mergulho com mantas), Munduk (cachoeiras e café balinês). Pousadas boutique cuidadosamente selecionadas.',
            emotionalIntro: 'Você acorda sem despertador porque os pássaros cantam. Faz yoga de frente para o vulcão. Come um nasi goreng por A$3 que é melhor que qualquer restaurante caro. Bali faz isso com você.',
            currency: 'AUD',
            duration: 12,
            nights: 11,
            priceMin: 2900,
            priceMax: 4500,
            continent: 'Ásia',
            airport: 'DPS',
            travelStyles: ['Wellness', 'Cultural', 'Praia'],
            categories: ['Ásia', 'Praia', 'Wellness', 'Solo', 'Casais'],
            includes: ['Voo incluso', 'Hotel Boutique e Villa', 'Aulas de yoga', 'Café da manhã', 'Transfers'],
            includedItems: ['Retiro de yoga em Ubud', 'Mergulho com Manta Rays', 'Temple tour completo', 'Aula de culinária balinesa', 'Beach club em Seminyak'],
            highlights: ['Terraço de arroz de Tegalalang', 'Templo Tanah Lot no pôr do sol', 'Mergulho em Nusa Penida', 'Spa balinês tradicional'],
            perfectFor: ['Quem quer desacelerar', 'Yoguis e naturistas', 'Solo travelers em busca de conexão'],
            notRecommendedFor: ['Quem quer agitação urbana', 'Viajantes que não curtem calor e umidade'],
            importantInfo: ['Melhor época: abr–out (seco)', 'Brasileiros: 30 dias de isenção de visto', 'Sarongue obrigatório em templos (fornecemos)'],
            featured: false,
            hasFreeCancellation: true,
            isAllInclusive: false,
            badge: 'VERIFIED',
            rating: 4.82,
            reviewCount: 66,
            recentPurchases: 14,
            qualityScore: 89,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
        {
            agencyId: agency1.id,
            title: 'Costa Rica Selvagem — Selva, Surf e Vulcões',
            destination: 'San José',
            country: 'Costa Rica',
            description: 'O país que protege 25% do seu território. Pura Vida não é só uma expressão — é uma filosofia de vida. Aqui você surfa de manhã, vê preguiças ao meio-dia e mergulha em thermal pools ao entardecer.',
            fullDescription: 'Road trip completo: Arenal Volcano + thermal pools, Monteverde Cloud Forest (pontes suspensas, tirolesa), Manuel Antonio (peguiças, macacos, praias), Santa Teresa (surf, pôr do sol épico), Tortuguero (tartarugas marinhas).',
            emotionalIntro: 'Uma preguiça te olha de um galho a 30 cm. Uma arara escarlate passa voando. O vulcão Arenal solta fumaça ao fundo. A Costa Rica não mostra a natureza — ela te mergulha dentro dela.',
            currency: 'AUD',
            duration: 14,
            nights: 13,
            priceMin: 2700,
            priceMax: 4100,
            continent: 'América Central',
            airport: 'SJO',
            multiDestination: true,
            additionalCities: ['La Fortuna', 'Monteverde', 'Manuel Antonio', 'Santa Teresa'],
            travelStyles: ['Aventura', 'Natureza'],
            categories: ['Aventura', 'Natureza', 'América Central', 'Surf', 'Ecoturismo'],
            includes: ['Voo incluso', 'Lodges e eco-hotel', 'Carro 4x4', 'Guia de fauna', 'Café da manhã'],
            includedItems: ['Tirolesa em Monteverde', 'Thermal pools Arenal', 'Canopy tour', 'Snorkeling em Manuel Antonio', 'Observação de tartarugas (época)'],
            highlights: ['Vulcão Arenal ativo', 'Sloths em Manuel Antonio', 'Surf em Santa Teresa', 'Cloud Forest suspenso'],
            perfectFor: ['Aventureiros com amor à natureza', 'Surfistas', 'Famílias com crianças maiores'],
            notRecommendedFor: ['Quem prefere cidades e luxo', 'Quem tem problema com insetos e umidade'],
            importantInfo: ['Melhor época: dez–abr (seco)', 'Motorista com CNH (aceitam brasileira)', 'Brasileiros isentos de visto por 30 dias'],
            featured: false,
            hasFreeCancellation: true,
            isAllInclusive: false,
            badge: 'VERIFIED',
            rating: 4.79,
            reviewCount: 54,
            recentPurchases: 8,
            qualityScore: 87,
            status: 'APPROVED',
            approvedAt: new Date(),
        },
    ];

    for (const pkg of packages) {
        const existing = await prisma.package.findFirst({ where: { title: pkg.title } });
        if (!existing) {
            await prisma.package.create({ data: pkg as any });
            console.log(`✅ Pacote criado: ${pkg.title}`);
        } else {
            console.log(`⏭️  Já existe: ${pkg.title}`);
        }
    }

    // ─── 5 NOVOS ROTEIROS ──────────────────────────────────────────────────────

    const itineraries = [
        {
            creatorId: creators[0].id,
            title: 'Nova York em 5 Dias — Manhattã do Zero',
            destination: 'Nova York',
            country: 'Estados Unidos',
            description: 'Pára de adiar Nova York. Este roteiro foi feito para quem quer curtir NYC ao máximo em 5 dias — sem ficar em fila, sem se perder e sem pagar caro à toa.',
            subtitle: 'Da Times Square ao Brooklyn Bridge — o guia que nenhum blog te dá.',
            currency: 'AUD',
            price: 29,
            duration: 5,
            travelStyles: ['Cultural', 'City Trip'],
            categories: ['América do Norte', 'Solo', 'Casais', 'Amigos', 'City Trip'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'dicas', 'checklist', 'gasto'],
            highlights: ['Central Park ao amanhecer (sem multidão)', 'High Line + Chelsea Market', 'Brooklyn Bridge Walk', 'Jane\'s Carousel com skyline épico'],
            inclusions: ['Roteiro 5 dias', 'Mapa do metrô de NYC descomplicado', 'Guia de gorjetas e etiqueta', 'Lista de diners históricos', 'Dicas para economizar em NYC'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 92,
            featured: true,
            rating: 4.91,
            reviewCount: 567,
            downloadCount: 1843,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 200, max: 400, currency: 'USD',
                breakdown: [
                    { category: 'Hospedagem', amount: 150, description: 'Hostel em Manhattan ou Queens (50–100 USD/noite)' },
                    { category: 'Alimentação', amount: 80, description: 'Bagels + pizza slice + diner americano' },
                    { category: 'Transporte', amount: 35, description: 'Metrocard semanal + ferry Staten Island (grátis)' },
                    { category: 'Atrações', amount: 60, description: 'Top of the Rock + Estatua da Liberdade + museus' },
                    { category: 'Extras', amount: 75, description: 'Broadway com antecedência + compras no Soho' },
                ],
            },
        },
        {
            creatorId: creators[1].id,
            title: 'Vietnã de Norte a Sul — 14 Dias Sem Filtro',
            destination: 'Hanói',
            country: 'Vietnã',
            description: 'Do caos de Hanói à paz de Hội An. Da Baía de Ha Long ao fervilhante Ho Chi Minh City. Este roteiro atravessa o Vietnã de cima a baixo com honestidade e detalhes que nenhuma agência conta.',
            subtitle: 'Phở de manhã, lanterna flutuante de noite.',
            currency: 'AUD',
            price: 35,
            duration: 14,
            travelStyles: ['Cultural', 'Aventura', 'Gastronômico'],
            categories: ['Ásia', 'Solo', 'Casais', 'Aventura', 'Gastronômico'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'transporte', 'hospedagem', 'restaurantes', 'dicas', 'checklist', 'gasto'],
            highlights: ['Cruzeiro na Baía de Ha Long', 'Lanternas flutuantes em Hội An', 'Moped tour pelo Old Quarter de Hanói', 'War Remnants Museum em HCMC'],
            inclusions: ['Roteiro 14 dias', 'Guia de voos domésticos (Vietnam Airlines vs jetstar)', 'Mapa dos trens lentos de Da Nang', 'Street food seguro — o guia definitivo', 'Frases em vietnamita'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 93,
            featured: false,
            rating: 4.88,
            reviewCount: 312,
            downloadCount: 1021,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 230, max: 460, currency: 'AUD',
                breakdown: [
                    { category: 'Hospedagem', amount: 115, description: 'Hostels e guesthouses (8–26 AUD/noite)' },
                    { category: 'Alimentação', amount: 80, description: 'Phở, bánh mì, nem cuốn, muito frango' },
                    { category: 'Transporte', amount: 80, description: 'Voos domésticos + trens + grab' },
                    { category: 'Cruzeiro Ha Long', amount: 115, description: 'Budget ou premium — cobro os dois' },
                    { category: 'Extras', amount: 65, description: 'Lanterna de Ha Long + passeios + compras' },
                ],
            },
        },
        {
            creatorId: creators[0].id,
            title: 'México de Verdade — Cidade, Oaxaca & Cenotes',
            destination: 'Cidade do México',
            country: 'México',
            description: 'Esqueça Cancun. O México real é taco de guisado às 7h na Merced, mezcal artesanal em Oaxaca e mergulho num cenote sem turista nenhum. Este roteiro vai mudar sua visão do país.',
            subtitle: 'México do jeito que os mexicanos vivem.',
            currency: 'AUD',
            price: 25,
            duration: 10,
            travelStyles: ['Cultural', 'Gastronômico', 'Aventura'],
            categories: ['América do Norte', 'Solo', 'Casais', 'Cultural', 'Gastronômico'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'restaurantes', 'dicas', 'checklist', 'gasto'],
            highlights: ['Mercado de Coyoacán sem turista', 'Mezcaleria escondida em Oaxaca', 'Cenote secreto no Yucatán', 'Murais de Diego Rivera'],
            inclusions: ['Roteiro 10 dias', 'Lista de taquerias que os locais frequentam', 'Guia de segurança em CDMX', 'Frases em espanhol mexicano', 'Transporte ADO vs voo interno'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 88,
            featured: false,
            rating: 4.84,
            reviewCount: 203,
            downloadCount: 612,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 80, max: 160, currency: 'USD',
                breakdown: [
                    { category: 'Hospedagem', amount: 45, description: 'Hostels de design e Airbnbs em Roma Norte' },
                    { category: 'Alimentação', amount: 25, description: 'Tacos (1.5 USD), mole oaxaqueño (8 USD), mezcal (5 USD)' },
                    { category: 'Transporte', amount: 30, description: 'Metro + ADO + colectivo cenotes' },
                    { category: 'Mercados e Museus', amount: 15, description: 'Frida Kahlo, Anahuacalli, Monte Albán' },
                    { category: 'Extras', amount: 45, description: 'Cenote + artesanato + mezcal de garrafa pra levar' },
                ],
            },
        },
        {
            creatorId: creators[1].id,
            title: 'Escócia — Highlands, Castelos e Whisky',
            destination: 'Edimburgo',
            country: 'Reino Unido',
            description: 'A Escócia é o roteiro mais cinematográfico do mundo. Lochs, castelos em ruínas, whisky single malt e o povo mais acolhedor da Europa. Este roteiro é para os que se cansaram do convencional.',
            subtitle: 'Nebulosa, dramática e absolutamente inesquecível.',
            currency: 'AUD',
            price: 27,
            duration: 9,
            travelStyles: ['Cultural', 'Aventura', 'Natureza'],
            categories: ['Europa', 'Solo', 'Casais', 'Cultural', 'Natureza'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospedagem', 'transporte', 'dicas', 'checklist'],
            highlights: ['Ilha de Skye (pura magia)', 'Rota do Whisky (Speyside)', 'Castelo de Eilean Donan', 'Edimburgo Old Town de noite'],
            inclusions: ['Roteiro 9 dias', 'Sugestões de B&Bs e guesthouses', 'Guia de degustação de whisky', 'Mapa dos Highlands com GPS', 'O que vestir (sério, é importante)'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 86,
            featured: false,
            rating: 4.79,
            reviewCount: 118,
            downloadCount: 374,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 120, max: 220, currency: 'GBP',
                breakdown: [
                    { category: 'Hospedagem', amount: 80, description: 'B&Bs gostosos com café da manhã escocês' },
                    { category: 'Carro alugado', amount: 50, description: 'Indispensável para os Highlands' },
                    { category: 'Alimentação', amount: 40, description: 'Fish & chips, haggis, cullen skink' },
                    { category: 'Whisky', amount: 30, description: 'Tours nas destilarias + garrafas de lembrança' },
                    { category: 'Atrações', amount: 20, description: 'Castelos + ferry Ilha de Skye' },
                ],
            },
        },
        {
            creatorId: creators[0].id,
            title: 'Amsterdã & Bélgica — Arte, Cerveja e Canais',
            destination: 'Amsterdã',
            country: 'Holanda',
            description: 'Duas semanas percorrendo os países mais aconchegantes da Europa: canais de Amsterdã, campos de tulipas, Bruges medieval, chocolate belga e as cervejas Trappist mais incríveis do mundo.',
            subtitle: 'Do Van Gogh ao Manneken Pis — Europa do jeito que você imaginou.',
            currency: 'AUD',
            price: 29,
            duration: 10,
            travelStyles: ['Cultural', 'Gastronômico'],
            categories: ['Europa', 'Casais', 'Amigos', 'Cultural', 'Gastronomia'],
            productType: 'DIGITAL',
            activeModules: ['itinerario', 'mapa', 'hospdagem', 'transporte', 'restaurantes', 'dicas', 'checklist', 'gasto'],
            highlights: ['Keukenhof (tulipas se for na época)', 'Bruges ao amanhecer sem turista', 'Brewery tour Trappist', 'Van Gogh Museum sem fila'],
            inclusions: ['Roteiro 10 dias', 'Dica de compra antecipada de museus', 'Guia de bares de cerveja artesanal em Bruxelas', 'Passeio de bicicleta em Amsterdã', 'Frases em holandês e francês'],
            immediateAccess: true,
            lifetimeAccess: true,
            offlineDownload: true,
            allowShare: false,
            allowPdf: true,
            qualityScore: 85,
            featured: false,
            rating: 4.76,
            reviewCount: 95,
            downloadCount: 287,
            status: 'APPROVED',
            approvedAt: new Date(),
            estimatedSpending: {
                min: 130, max: 220, currency: 'EUR',
                breakdown: [
                    { category: 'Hospedagem', amount: 80, description: 'Hostels centrais ou Airbnb nos canais' },
                    { category: 'Alimentação', amount: 45, description: 'Stroopwafel, bitterballen, moules-frites, chocolate' },
                    { category: 'Transporte', amount: 35, description: 'Inter-rail + bicicleta + metrô' },
                    { category: 'Museus', amount: 30, description: 'Van Gogh, Rijksmuseum, Atomium' },
                    { category: 'Cervejas e saídas', amount: 30, description: 'Degustações + jenever em bruin cafés' },
                ],
            },
        },
    ];

    for (const it of itineraries) {
        const existing = await prisma.itinerary.findFirst({ where: { title: it.title } });
        if (!existing) {
            await prisma.itinerary.create({ data: it as any });
            console.log(`✅ Roteiro criado: ${it.title}`);
        } else {
            console.log(`⏭️  Já existe: ${it.title}`);
        }
    }

    console.log('\n🎉 Seed extra completo!');
    console.log(`📦 5 pacotes adicionais`);
    console.log(`🗺️  5 roteiros adicionais`);
}

main()
    .catch(e => { console.error(e); process.exit(1); })
    .finally(() => prisma.$disconnect());
